/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as BlogBestAiWorkspacesRouteImport } from './routes/blog/best-ai-workspaces'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminPackagesRouteImport } from './routes/admin/packages'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminFlagsRouteImport } from './routes/admin/flags'
import { Route as AdminFaqsRouteImport } from './routes/admin/faqs'
import { Route as AdminBroadcastRouteImport } from './routes/admin/broadcast'
import { Route as AdminBlogRouteImport } from './routes/admin/blog'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedCreditsRouteImport } from './routes/_authenticated/credits'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatChatIdRouteImport } from './routes/_authenticated/chat.$chatId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BlogBestAiWorkspacesRoute = BlogBestAiWorkspacesRouteImport.update({
  id: '/blog/best-ai-workspaces',
  path: '/blog/best-ai-workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPackagesRoute = AdminPackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFlagsRoute = AdminFlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBroadcastRoute = AdminBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCreditsRoute = AuthenticatedCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)
const AuthenticatedChatChatIdRoute = AuthenticatedChatChatIdRouteImport.update({
  id: '/$chatId',
  path: '/$chatId',
  getParentRoute: () => AuthenticatedChatRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/credits': typeof AuthenticatedCreditsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/best-ai-workspaces': typeof BlogBestAiWorkspacesRoute
  '/admin/': typeof AdminIndexRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/credits': typeof AuthenticatedCreditsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/best-ai-workspaces': typeof BlogBestAiWorkspacesRoute
  '/admin': typeof AdminIndexRoute
  '/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/credits': typeof AuthenticatedCreditsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/broadcast': typeof AdminBroadcastRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/flags': typeof AdminFlagsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/packages': typeof AdminPackagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/best-ai-workspaces': typeof BlogBestAiWorkspacesRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/chat/$chatId': typeof AuthenticatedChatChatIdRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/chat'
    | '/credits'
    | '/settings'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/broadcast'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/api/chat'
    | '/blog/best-ai-workspaces'
    | '/admin/'
    | '/chat/$chatId'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/credits'
    | '/settings'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/broadcast'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/api/chat'
    | '/blog/best-ai-workspaces'
    | '/admin'
    | '/chat/$chatId'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/chat'
    | '/_authenticated/credits'
    | '/_authenticated/settings'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/blog'
    | '/admin/broadcast'
    | '/admin/faqs'
    | '/admin/flags'
    | '/admin/login'
    | '/admin/packages'
    | '/admin/payments'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/api/chat'
    | '/blog/best-ai-workspaces'
    | '/admin/'
    | '/_authenticated/chat/$chatId'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogBestAiWorkspacesRoute: typeof BlogBestAiWorkspacesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/blog/best-ai-workspaces': {
      id: '/blog/best-ai-workspaces'
      path: '/blog/best-ai-workspaces'
      fullPath: '/blog/best-ai-workspaces'
      preLoaderRoute: typeof BlogBestAiWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/packages': {
      id: '/admin/packages'
      path: '/packages'
      fullPath: '/admin/packages'
      preLoaderRoute: typeof AdminPackagesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/flags': {
      id: '/admin/flags'
      path: '/flags'
      fullPath: '/admin/flags'
      preLoaderRoute: typeof AdminFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/broadcast': {
      id: '/admin/broadcast'
      path: '/broadcast'
      fullPath: '/admin/broadcast'
      preLoaderRoute: typeof AdminBroadcastRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credits': {
      id: '/_authenticated/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof AuthenticatedCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/_authenticated/chat/$chatId': {
      id: '/_authenticated/chat/$chatId'
      path: '/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof AuthenticatedChatChatIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatChatIdRoute: typeof AuthenticatedChatChatIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatChatIdRoute: AuthenticatedChatChatIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedCreditsRoute: typeof AuthenticatedCreditsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedCreditsRoute: AuthenticatedCreditsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminBroadcastRoute: typeof AdminBroadcastRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminFlagsRoute: typeof AdminFlagsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPackagesRoute: typeof AdminPackagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminBroadcastRoute: AdminBroadcastRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminFlagsRoute: AdminFlagsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPackagesRoute: AdminPackagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiChatRoute: ApiChatRoute,
  BlogBestAiWorkspacesRoute: BlogBestAiWorkspacesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
